<?php

const VESTIDO = "VESTIDO";
const VES_ID = "VES_ID";
const VES_MODELO = "VES_MODELO";
const VES_DESCRIPCION = "VES_DESCRIPCION";
const VES_PRECIO = "VES_PRECIO";
const VES_ESTADO = "VES_ESTADO";
const VES_FECHA_CREACION = "VES_FECHA_CREACION";
