<?php

const CONTACTO = "CONTACTO";
const CON_ID = "CON_ID";
const CON_NOMBRE = "CON_NOMBRE";
const CON_APELLIDOS = "CON_APELLIDOS";
const CON_CORREO = "CON_CORREO";
const CON_TELEFONO = "CON_TELEFONO";
const CON_MENSAJE = "CON_MENSAJE";
