<?php

const ACCESORIO = "ACCESORIO";
const ACC_ID = "ACC_ID";
const ACC_MODELO = "ACC_MODELO";
const ACC_DESCRIPCION = "ACC_DESCRIPCION";
const ACC_PRECIO = "ACC_PRECIO";
const ACC_ESTADO = "ACC_ESTADO";
const ACC_FECHA_CREACION = "ACC_FECHA_CREACION";
