<?php

const COLOR = "COLOR";
const COL_ID = "COL_ID";
const COL_NOMBRE = "COL_NOMBRE";
const COL_HEXADECIMAL = "COL_HEXADECIMAL";
const COL_DESCRIPCION = "COL_DESCRIPCION";
const COL_ESTADO = "COL_ESTADO";
