<?php

const USUARIO = "USUARIO";
const USU_ID = "USU_ID";
const USU_CUE = "USU_CUE";
const USU_MATCH = "USU_MATCH";
const USU_CORREO = "USU_CORREO";
const USU_TELEFONO = "USU_TELEFONO";
const USU_ESTADO = "USU_ESTADO";
const USU_FECHA_CREACION = "USU_FECHA_CREACION";
